batch_size: 1
coord_dim: 3
data_folder: Data/ellipse_data
dimension: 2
hidden_size: 32
inference_file: Data/ellipse_data/ellipse_data_unseen2.csv
lhs_sample: 500000
num_epochs: 10
num_hidden_layers: 3
output_dim: 5
param_columns:
- a
- b
param_dim: 1
print_every: 1
project_name: semi_ellipse1
shuffle: false
test_size: 0.2
