batch_size: 36
coord_dim: 4
data_folder: Data/sphere_formation_data
dimension: 2
hidden_size: 32
inference_file: Data/sphere_formation_data/sf0.csv
lhs_sample: 500000
lr: 0.001
num_epochs: 5
num_hidden_layers: 3
output_dim: 5
param_columns:
- x
- y
param_dim: 2
print_every: 1
project_name: sphere_formation_sdf
shuffle: true
test_size: 0.2
