batch_size: 16
coord_dim: 3
data_folder: Data/x_43_data_36
dimension: 2
distance_columns:
- distanceToSurface
distance_dim: 1
hidden_size: 128
lhs_sample: 500000
loss_type: mse
low_fi_data_folder: Data/x_43_low_fi_72
lr: 0.0001
lr_gamma: 1.5
model_type: low_fi_fusion
num_epochs: 50000
num_hidden_layers: 8
output_dim: 6
param_columns:
- a2
- a3
- a4
param_dim: 3
print_every: 1
project_name: hyperparam_sweep_23
shuffle: true
test_size: 0.2
