batch_size: 36
coord_dim: 3
data_folder: Data/ellipse_data
dimension: 2
distance_columns:
- distanceToEllipse
distance_dim: 1
hidden_size: 32
lhs_sample: 500000
loss_type: mse
lr: 0.0001
lr_gamma: 1.5
model_type: vanilla
num_epochs: 3
num_hidden_layers: 3
output_dim: 6
param_columns:
- a
- b
param_dim: 2
print_every: 1
project_name: sweep_1
shuffle: false
test_size: 0.2
