batch_size: 1
coord_dim: 3
distance_dim: 1
distance_columns:
- distanceToEllipse
data_folder: Data/ellipse_data
dimension: 2
hidden_size: 32
inference_file: Data/ellipse_data/ellipse_data_unseen2.csv
lhs_sample: 500000
num_epochs: 5
num_hidden_layers: 3
output_dim: 5
param_columns:
- a
- b
param_dim: 2
print_every: 1
project_name: semi_ellipse_sdf
shuffle: false
test_size: 0.2
lr: 0.0001
