batch_size: 36
coord_dim: 3
data_folder: Data/x_43_data_36
low_fi_data_folder: Data/x_43_low_fi_72
dimension: 2
distance_columns:
- distanceToSurface
distance_dim: 1
hidden_size: 32
lhs_sample: 500000
loss_type: mse
lr: 0.0001
lr_gamma: 1.2
model_type: low_fi_fusion
num_epochs: 3
num_hidden_layers: 3
output_dim: 6
param_columns:
- a2
- a3
- a4
param_dim: 3
print_every: 1
project_name: x_43
shuffle: true
test_size: 0.2
